version: '3.8'
services:
  routine-service-db:
    image: postgres:14
    container_name: routine-service-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5435:5432
    volumes:
      - routine-service-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
    - schedule-internal-net
    - auth-share-net

  routine-service:
    build: .
    container_name: routine-service
    restart: always
    ports:
    - 8003:8003
    networks:
    - schedule-internal-net
    - auth-share-net
    depends_on:
    - routine-service-db
    env_file:
      - .env
    # environment:
    #   DB_NAME: routine-service_db
    #   DB_USER: postgres
    #   DB_PASSWORD: sksk0877
    

networks:
  schedule-internal-net:
    external: true
  auth-share-net:
    external: true

volumes:
  routine-service-db-data:
